[package]
name = "forkscanner"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoincore-rpc = "0.14.0"
chrono = "0.4"
crossbeam-channel = "0.5.1"
diesel = { version = "1.4.8", features = ["chrono", "postgres"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.14"
serde_json = "1.0"
thiserror = "1.0.29"

[dev-dependencies]
jsonrpc = "0.12.0"
jsonrpc-http-server = "18.0.0"
serde_json = "1.0.68"
