[package]
name = "forkscanner"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.27"
bitcoincore-rpc = "0.14"
chrono = "0.4"
crossbeam-channel = "0.5"
diesel = { version = "1.4", features = ["chrono", "postgres"] }
dotenv = "0.15"
env_logger = "0.9"
jsonrpc = "0.12"
log = "0.4"
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
jsonrpc-http-server = "18.0.0"
serde_json = "1.0.68"
