---
services:
  scanner:
    image: scanner
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8339:8339"
      - "8340:8340"
    volumes:
      - log-data:/log
    networks:
      - scanner
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: forkscanner
      POSTGRES_USER: forkscanner
      POSTGRES_DB: forkscanner
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "relayer", "-U", "relayer"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - scanner
volumes:
  log-data:
  db-data:
networks:
  scanner:
